project_id = "wppwfiiomxmnjyokxnin"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.idea-chat]
verify_jwt = true

[functions.search-web]
verify_jwt = false

[functions.google-trends]
verify_jwt = false

[functions.reddit-search]
verify_jwt = false

[functions.youtube-search]
verify_jwt = false

[functions.twitter-search]
verify_jwt = false

[functions.tiktok-trends]
verify_jwt = false

[functions.amazon-public]
verify_jwt = false

[functions.generate-suggestions]
verify_jwt = false