project_id = "wppwfiiomxmnjyokxnin"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"
max_events_per_second = 100

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = true

[auth]
enabled = true
site_url = "https://wppwfiiomxmnjyokxnin.supabase.co"
additional_redirect_urls = ["https://auth-callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "1h"

[auth.email.template.invite]
subject = "You have been invited"
content_path = "./supabase/templates/invite.html"

[auth.sms]
enable_signup = true
enable_confirmations = false
max_frequency = "5s"

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.figma]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
skip_nonce_check = false

[auth.external.kakao]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.linkedin_oidc]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.slack_oidc]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
url = ""

[functions."check-subscription"]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.sync-subscription-role]
verify_jwt = true

[functions.dashboard-insights]
verify_jwt = false

[functions.enterprise-features]
verify_jwt = true

[functions.google-trends]
verify_jwt = false

[functions.idea-chat]
verify_jwt = true

[functions.help-support]
verify_jwt = true

[functions.reddit-search]
verify_jwt = false

[functions.search-web]
verify_jwt = false

[functions.subscription-benefits]
verify_jwt = true

[functions.populate-startup-ideas]
verify_jwt = true

[functions.tiktok-trends]
verify_jwt = false

[functions.twitter-search]
verify_jwt = false

[functions.youtube-search]
verify_jwt = false

[functions.generate-suggestions]
verify_jwt = false

[functions.generate-session-name]
verify_jwt = true

[functions.generate-session-title]
verify_jwt = true

[functions.generate-session-composite-name]
verify_jwt = true

[functions.amazon-public]
verify_jwt = false

[functions.analyze-idea]
verify_jwt = true

[functions.generate-analysis-suggestions]
verify_jwt = false

[functions.market-trends]
verify_jwt = true

[functions.competitor-analysis]
verify_jwt = true

[functions.financial-analysis]
verify_jwt = true

[functions.social-sentiment]
verify_jwt = true

[functions.execution-insights]
verify_jwt = true

[functions.market-insights]
verify_jwt = true

[functions.hub-data-fetcher]
verify_jwt = true

[functions.web-search-ai]
verify_jwt = true

[functions.evaluate-wrinkle-points]
verify_jwt = true

[functions.enhance-salty-response]
verify_jwt = true

[functions.web-search-optimized]
verify_jwt = true

[functions.dashboard-insights-realtime]
verify_jwt = true

[functions.serper-search]
verify_jwt = true

[functions.tavily-search]
verify_jwt = true

[functions.firecrawl-fetch]
verify_jwt = true

[functions.gdelt-news]
verify_jwt = false

[functions.web-search]
verify_jwt = false

[functions.groq-synthesis]
verify_jwt = true

[functions.web-search-profitability]
verify_jwt = false

[functions.reddit-sentiment]
verify_jwt = false

[functions.market-size]
verify_jwt = false

[functions.growth-projections]
verify_jwt = false

[functions.user-engagement]
verify_jwt = false

[functions.launch-timeline]
verify_jwt = false

[functions.pmf-score]
verify_jwt = false

[functions.competition]
verify_jwt = false

[functions.sentiment]
verify_jwt = false

[functions.hub-batch-data]
verify_jwt = false

[functions.generate-ai-insights]
verify_jwt = true

[functions.generate-recommendations]
verify_jwt = true

[functions.groq-batch-analysis]
verify_jwt = false

[functions.smoothbrains-score]
verify_jwt = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcloud.json"